### ISSUE TITLE
Identify method for aggregating source docs

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/documentation#24]
The current documentation, hosted on https://docs.phylum.io, consists of content from multiple sources:

* Public `phylum-dev` repositories
  * `phylum-dev/documentation` repo
    * Knowledge Base --> Policy section
    * "Home" category
  * `phylum-dev/cli` repo
    * "Support" category
    * Some of the "Knowledge Base" category
    * "Extensions" category
    * "Command Line Tool" category
  * `phylum-dev/phylum-ci` repo
    * "Integration" category
* Private `phylum-dev` repositories
  * A repo where the "analytics" (rules) are hosted
    * "Analytics" category
* Directly hosted pages on the site, created/edited within the Readme UI
  * Two pages in the "Knowledge Base" category
    * Phylum Package Score
    * Processing

This works because each repo has workflow(s) that push docs to the central Readme.com server using the `rdme` CLI. That is possible because the pages are centrally hosted (e.g., in a document storage schema) and asynchronous updates are allowed.

The new documentation will be hosted on GitHub Pages using Docusaurus, which is a static site generator. That means all the content needed to generate the site/docs is required to be in place at the time of generation. This poses a challenge given the current distributed nature of the individual documentation pages. There are several options for proceeding:

## Option 1: Move all documentation files to the `phylum-dev/documentation` repo

Consolidate _all_ docs from each source repo into a single place, the `phylum-dev/documentation` repo.

Pros:
* There is one place to go to update docs
* The generation procedure is greatly simplified
* Sidebar management and specification is easier to reason about
* The documentation can remain in a public repo
  * The "edit this page" link will work, allowing easier/more contributions

Cons:
* Documentation is not co-located with the code it documents
* It is more likely that developers will forget to update the docs
* Lose the ability to autogenerate templated docs
  * All the "Command Line Tool" category pages
  * Maybe also the "Analytics" category pages?

## Option 2: Use a Docusaurus plugin

There is [one plugin available](https://github.com/rdilweb/docusaurus-plugin-remote-content/) to allow for downloading content from remote sources.

Pros:
* This is a plugin [advertised by Docusaurus](https://docusaurus.io/docs/api/plugins)

Cons:
* It is only possible to specify _specific_ files and not a directory or file glob
  * Adding new pages in remote repos requires a manual update
  * It is easy for pages to go out of sync over time due to file name or location changes
* The plugin is not updated very often and may go unsupported
  * The latest release was on 12 APR 2022
  * The last (non-dep bump) was seven months ago

## Option 3: Use git submodules

Each repo hosting docs outside of `phylum-dev/documentation` could be added to `phylum-dev/documentation` as a git submodule.

Pros
* After updating each submodule, relative links would continue to work and show nicely in IDEs
* Docs continue to live with code, making updates easier and more likely

Cons
* Somewhat cumbersome to use
* Might be a bad idea to include private repos
* Still requires a method for triggering site generation when the source repos change

## Option 4: Create a custom workflow that pulls content in

Create a triggerable workflow in the `phylum-dev/documentation` repo that checks out each of the remote repos hosting docs to copy their files over prior to generating the site.

Pros:
* Docs continue to live with code, making updates easier and more likely

Cons:
* Sidebar management is harder
* Specifying links to content from external repos is more error prone and the IDE niceties are lost
* There is more overhead/complexity added to each remote repo to ensure they trigger the custom workflow when their docs change 

## Option 5: Create multiple statically hosted sites

Create one for the `documentation` repo and one for each of the dynamically generated pages. At this point, that might just be `cli`.

Pros:
* Dynamically generated docs can continue to be generated in their own repo(s)

Cons:
* Splitting the documentation site up can be confusing to users
* The various sites might not stay in sync (e.g., releases, look and feel, links)
* Linking between sites is more error prone

## Option 6: Combine some of the options above

Move the content that doesn't need to live in remote repos into the `documentation` repo. Create separate statically hosted sites for the remaining repo(s). Create "stub" pages in the main `documentation` repo to point to the full content.

## Option 7: Something else

Maybe there is another option to consider that is not enumerated here.
Maybe using a monorepo would help.
Maybe using a Static Site Generator (SSG) is _not_ the way to go.

**Comment by maxrake** [comment]
After some initial discussions with @kylewillmon, @furi0us333, and @louislang, the thought was to proceed with option 6. The content that does not need to live in remote repos is considered to be _all_ documentation content _except_ those pages that are dynamically generated within the remote repo. To be clear about this plan...each of the currently published pages is outlined here, with the action that will be taken on it.

Moving this issue to review...
Please provide acceptance or feedback on this plan. The goal is to have consensus and approval _before_ making changes to the source repos and possibly surprising folks. Tracking stakeholders, including team leads and primary contacts for affected repositories.

* [ ] @furi0us333 
* [ ] @louislang 
* [ ] @kylewillmon 
  * [ ] Please provide a preference for the "Extensions" category options
* [ ] @texasbeef45 
* [ ] @maxrake 

## "Home" category
* These pages already exist in `documentation` repo
* They will stay there

## "Command Line Tool" category
* "Quickstart" page
  * Move from `cli` to `documentation` repo
* "Alternate Installation Methods" page
  * Move from `cli` to `documentation` repo 
* All other pages (the `phylum` command reference pages)
  * These are dynamically generated from templates
  * They will stay in the `cli` repo
  * A separate statically generated site will be created to host these pages
    * It will also be a Docusaurus site, but hosted from the `cli` repo
  * Page(s) on the main `documentation` site will reference and point to the `cli` site

## "Integrations" category
* Move all of these pages from the `phylum-ci` repo to the `documentation` repo

## "Extensions" category
* These pages are not dynamically generated so there is a case that they should be moved to `documentation` repo
* OTOH, since the plan is to already have a separate `cli` Docusaurus site, it might make sense to keep these pages in the `cli` repo

## "Knowledge Base" category
* "Analyzing Dependencies" page
  * Do the same thing that is decided for the "Extensions" category
* "Lockfile Generation" page (not yet published to Readme.com site)
  * Do the same thing that is decided for the "Extensions" category
* "API Keys" page
  * Move from `cli` to `documentation` repo
* "Groups" page
  * Move from `cli` to `documentation` repo
* "Phylum Package Score" page
  * Abandon this page (do not port it)
* "Policy" section
  * These pages already exist in `documentation` repo
  * They will stay there
* "Processing" page
  * Capture the content from within the Readme UI in a page in the `documentation` repo
  * Consider putting it in a larger page (e.g., FAQ)

## "Analytics" category
* Move all of these pages from their current repo to the `documentation` repo

## "Support" category
* "Security" page
  * Move from `cli` to `documentation` repo
* "Contact Us" page
  * Move from `cli` to `documentation` repo

**Comment by kylewillmon** [comment]
> The content that does not need to live in remote repos is considered to be _all_ documentation content _except_ those pages that are dynamically generated within the remote repo.

I don't think this is quite right... Since anything not in the `documentation` repo will be a separate statically generated site, we should make the decision **per category** to keep the documentation within each category together.

As for the "Extensions" category, I think it should stay in `cli`.

So to be clear: The "Command Line Tool" and "Extensions" categories should be in `cli`. Everything else should be in `documentation`.

**Comment by maxrake** [comment]
@kylewillmon, thank you for the feedback...the proposal has been updated to reflect it.

**Comment by maxrake** [comment]
I am okay with the changes. It will mean opening multiple PRs for some changes to the `phylum-ci` repository...and then coordinating/timing them with a release that includes the changes...but this is already the case for the GitHub Action documentation (since it lives in the `phylum-dev/phylum-analyze-pr-action` repo).

**Comment by maxrake** [comment]
This plan was discussed out of band and approved by @furi0us333

**Comment by maxrake** [comment]
Consensus has been reached. Moving to done...
