### ISSUE TITLE
Add a "Defend Your Workstation" page

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/documentation#43]
## Overview

Add a new content overview page for the "Defend Your Workstation" topic/concept. It will be less of a guide and meant more as a landing page to drive folks to the appropriate local protection method. This is meant to answer the question of how Phylum can defend the developer by shifting security even further left.

## Additional context

Provide more detail around the new content:

* The page will be a new landing page
  * The content will be action oriented, with more detail and distinction made about the context (local development) within which those integrations exist
  * Provide a compelling user story to help sell the value offered by the integrations
* Cover all of the current options
  * Direct CLI use
  * "pre-check" default extensions
  * Git pre-commit hook
  * Optional CLI extensions
* Step through the process to make it as clear as possible
  * It should be possible for someone with no knowledge of Phylum to read through one of these pages and follow along to completion
* A single page is okay for now
  * Move to the "self-identify" (e.g., tile based decision tree) model later, with individual pages/docs for each combination
* Get more guidance from @furi0us333 and/or the marketing team

**Comment by Wholesomebruh** [comment]
Please share the design file.

**Comment by maxrake** [comment]
The latest changes have been checked into the `defend_your_ws` branch. This issue will be on hold for a bit unless someone else wants to take it on.
